# This file is for teaching kustomize how to substitute names in the HelmRelease CRD
#
nameReference:
- kind: ConfigMap
  version: v1
  fieldSpecs:
  - path: spec/valuesFrom/name
    kind: HelmRelease
- kind: Secret
  version: v1
  fieldSpecs:
  - path: spec/valuesFrom/name
    kind: HelmRelease
- kind: HelmRepository
  fieldSpecs:
  - path: spec/chart/spec/sourceRef/name
    kind: HelmRelease
