apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app.fullname" . }}-nginx
  labels:
    {{- include "app.labels" . | nindent 4 }}
data:
  default.conf: |
    server {
      listen 8080 default_server;
      server_name _;
      location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ =404;
      }
      error_page 500 502 503 504 /50x.html;
      location = /50x.html { root /usr/share/nginx/html; }
    }
