apiVersion: v2
appVersion: 1.0.0
description: A reference for anyone preparing Word documents to be converted into HTML.
home: https://course-production-site.ltc.bcit.ca
icon: https://course-production.ltc.bcit.ca/favicon.ico
maintainers:
  - email: ltc_techops@bcit.ca
    name: BCIT LTC
    url: https://www.bcit.ca/learning-teaching-centre/
name: course-production-site
sources:
  - https://github.com/bcit-ltc/
  - https://github.com/bcit-ltc/course-production-site
version: 1.0.0
