{{/*
SPDX-License-Identifier: MPL-2.0
*/}}

{{- $seen := dict -}}
{{- $hasFEConfigs := gt (len (default (list) .Values.frontend.configs)) 0 -}}
{{- $hasPRConfigs := gt (len (default (list) .Values.processor.configs)) 0 -}}
{{- $anyConfigs := or $hasFEConfigs $hasPRConfigs -}}

{{- /* If user provided ANY configs, render ONLY those. Otherwise render a single default nginx-config. */ -}}

{{- if $anyConfigs }}
  {{- /* Render component configs (frontend + processor) */ -}}
  {{- $components := list (dict "name" "processor" "cfg" .Values.processor) (dict "name" "frontend" "cfg" .Values.frontend) -}}
  {{- range $comp := $components }}
    {{- $c := index $comp "cfg" -}}
    {{- range $cfg := (default (list) $c.configs) }}
      {{- $name := $cfg.name | default "" -}}
      {{- if and $name (not (hasKey $seen $name)) }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $name | quote }}
  labels:
    helm.sh/chart: {{ include "app.chart" $ }}
    app.kubernetes.io/name: {{ include "app.name" $ }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    app.kubernetes.io/version: {{ $.Chart.AppVersion }}
data:
{{ toYaml ($cfg.data | default dict) | nindent 2 }}
        {{- $_ := set $seen $name true }}
      {{- end }}
    {{- end }}

    {{- /* configEnvs are still rendered as configmaps when present */ -}}
    {{- range $cfg := (default (list) $c.configEnvs) }}
      {{- $name := $cfg.name | default "" -}}
      {{- if and $name (not (hasKey $seen $name)) }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $name | quote }}
  labels:
    helm.sh/chart: {{ include "app.chart" $ }}
    app.kubernetes.io/name: {{ include "app.name" $ }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    app.kubernetes.io/version: {{ $.Chart.AppVersion }}
data:
{{ toYaml (omit $cfg "name") | nindent 2 }}
        {{- $_ := set $seen $name true }}
      {{- end }}
    {{- end }}
  {{- end }}
{{- else }}
  {{- /* No user configs anywhere: render the single default nginx-config */ -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  labels:
    helm.sh/chart: {{ include "app.chart" . }}
    app.kubernetes.io/name: {{ include "app.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
data:
  default.conf: |
    server {
      listen 8080 default_server;
      server_name _;
      location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ =404;
      }
      error_page 500 502 503 504 /50x.html;
      location = /50x.html { root /usr/share/nginx/html; }
    }
{{- end }}
