apiVersion: v2
appVersion: 0.0.0-rc.01a9cdd.20250902234251
description: qcon-api is the backend API for the QCon application. It provides a websocket endpoint for converting documents from word to SCORM format.
home: https://qcon-api.ltc.bcit.ca
icon: https://course-production.ltc.bcit.ca/favicon.ico
maintainers:
  - email: ltc_techops@bcit.ca
    name: BCIT LTC
    url: https://www.bcit.ca/learning-teaching-centre/
name: qcon-api
sources:
  - https://github.com/bcit-ltc/
version: 0.0.0-rc.01a9cdd.20250902234251
