apiVersion: v2
appVersion: 1.1.0
description: qcon-api is the backend API for the QCon application. It provides a websocket endpoint for converting documents from word to SCORM format.
home: https://qcon-api.ltc.bcit.ca
icon: https://course-production.ltc.bcit.ca/favicon.ico
maintainers:
  - email: ltc_techops@bcit.ca
    name: BCIT LTC
    url: https://www.bcit.ca/learning-teaching-centre/
name: qcon-api
sources:
  - https://github.com/bcit-ltc/
  - https://github.com/bcit-ltc/qcon-api
version: 1.1.0
