{{- if .Values.backend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ default "backend" .Values.backend.service.name }}
  labels:
    helm.sh/chart: {{ include "app.chart" . }}
    app.kubernetes.io/name: {{ include "app.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  ports:
    - name: tcp-postgres
      port: {{ .Values.backend.service.port }}
      targetPort: tcp-postgres
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "app.name" . }}
    app.kubernetes.io/component: backend
{{- end }}
