{{- define "nginx-unprivileged.service.tpl" -}}
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
{{- end -}}
{{- define "nginx-unprivileged.service" -}}
{{- include "nginx-unprivileged.util.merge" (append . "nginx-unprivileged.service.tpl") -}}
{{- end -}}