apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app.name" . }}
  labels:
{{ include "app.labels" . | nindent 4 }}
  {{- $depAnn := include "app.deployment.annotations" . -}}
  {{- if $depAnn }}
{{ $depAnn | nindent 2 }}
  {{- end }}
spec:
  replicas: {{ .Values.processor.replicas | default 1 }}
  revisionHistoryLimit: {{ .Values.global.revisionHistoryLimit | default 3 }}
  progressDeadlineSeconds: {{ .Values.global.progressDeadlineSeconds | default 600 }}
  selector:
    matchLabels:
{{ include "app.selectorLabels" . | nindent 6 }}

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%

  template:
    metadata:
      labels:
{{ include "app.labels" . | nindent 8 }}
        {{- with .Values.processor.extraLabels }}
{{ toYaml . | nindent 8 }}
        {{- end }}
      {{- $podAnn := include "app.pod.annotations" . -}}
      {{- if $podAnn }}
{{ $podAnn | nindent 6 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "app.serviceAccount.name" . }}
      {{- with .Values.frontend.securityContext.pod }}
      securityContext:
{{ toYaml . | nindent 8 }}
      {{- end }}

      containers:
        {{- if (default false .Values.processor.enabled) }}
        - name: {{ include "app.name" . }}
          image: "{{ .Values.processor.image.registry }}/{{ .Values.processor.image.repository }}:{{ .Values.processor.image.tag }}"
          imagePullPolicy: {{ .Values.processor.image.pullPolicy | default "IfNotPresent" }}
          ports:
            - containerPort: {{ .Values.processor.port | default 8000 }}
          {{- $procEnvFrom := include "app.componentEnvFrom" .Values.processor }}
          {{- if $procEnvFrom }}
          envFrom:
{{ $procEnvFrom | nindent 12 }}
          {{- end }}
          env:
            - name: APP_VERSION
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['app.kubernetes.io/version']
{{- include "app.extraEnvironmentVars" .Values.processor | nindent 12 }}
          {{- $pm := include "app.componentVolumeMounts" .Values.processor -}}
          {{- $pd := include "app.dataStorage.processorVolumeMount" . -}}
          {{- if or $pm $pd }}
          volumeMounts:
{{- if $pm }}{{ $pm | nindent 12 }}{{- end }}
{{- if $pd }}{{ $pd | nindent 12 }}{{- end }}
          {{- end }}
        {{- end }}

        {{- if (default false .Values.frontend.enabled) }}
        - name: {{ default "frontend" .Values.frontend.name }}
          image: "{{ .Values.frontend.image.registry }}/{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy | default "IfNotPresent" }}
          ports:
            - containerPort: {{ .Values.frontend.port | default 8080 }}
          {{- $feEnvFrom := include "app.componentEnvFrom" .Values.frontend }}
          {{- if $feEnvFrom }}
          envFrom:
{{ $feEnvFrom | nindent 12 }}
          {{- end }}
          env:
            - name: APP_VERSION
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['app.kubernetes.io/version']
{{- include "app.extraEnvironmentVars" .Values.frontend | nindent 12 }}
          {{- with .Values.frontend.securityContext.container }}
          securityContext:
{{ toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.frontend.resources }}
          resources:
{{ toYaml . | nindent 12 }}
          {{- end }}
          {{- $fm := include "app.componentVolumeMounts" .Values.frontend | trim -}}
          {{- $fd := include "app.dataStorage.frontendVolumeMount" . -}}
          {{- if or $fm $fd }}
          volumeMounts:
{{- if $fm }}{{ $fm | nindent 12 }}{{- end }}
{{- if $fd }}{{ $fd | nindent 12 }}{{- end }}
          {{- else }}
          volumeMounts:
            - name: tmp
              mountPath: /tmp
            - name: nginx-config
              mountPath: /etc/nginx/conf.d
          {{- end }}
        {{- end }}

      {{- $pv := (include "app.podVolumes" .) | trim -}}
      {{- $pvc := (include "app.dataStorage.podVolume" .) | trim -}}
      {{- $def := (include "app.defaultFrontendVolumes" .) | trim -}}
      {{- if or $pv $pvc $def }}
      volumes:
        {{- if $pv  }}{{ $pv  | nindent 8 }}{{- end }}
        {{- if $pvc }}{{ $pvc | nindent 8 }}{{- end }}
        {{- if $def }}{{ $def | nindent 8 }}{{- end }}
      {{- end }}

      {{- include "imagePullSecrets" . | nindent 6 }}
