{{- if .Values.imagePullSecret.dockerconfigjson }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ default (printf "%s-image-pull-secret" (include "apps-common.app.name" .)) .Values.imagePullSecret.name }}
  labels:
    app.kubernetes.io/name: {{ include "apps-common.app.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.imagePullSecret.dockerconfigjson | quote }}
{{- end }}
