{{- if (default true .Values.serviceAccount.create) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "app.name" . }}
  labels:
{{ include "app.labels" . | nindent 4 }}
  {{ include "app.serviceAccount.annotations" . | nindent 2 }}
{{- end }}
