apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app.name" . }}
  labels:
    helm.sh/chart: {{ include "app.chart" . }}
    app.kubernetes.io/name: {{ include "app.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
  {{ include "app.deployment.annotations" . | nindent 2 }}
spec:
  replicas: {{ .Values.processor.replicas }}
  revisionHistoryLimit: {{ .Values.global.revisionHistoryLimit }}
  progressDeadlineSeconds: {{ .Values.global.progressDeadlineSeconds }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "app.name" . }}
      component: server
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        helm.sh/chart: {{ include "app.chart" . }}
        app.kubernetes.io/name: {{ include "app.name" . }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        component: server
        {{- with .Values.processor.extraLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{ include "app.pod.annotations" . | nindent 6 }}
    spec:
      serviceAccountName: {{ include "app.serviceAccount.name" . }}
      {{ include "frontend.securityContext.pod" . | nindent 6 }}

      containers:
        - name: {{ include "app.name" . }}
          image: "{{ .Values.processor.image.registry }}/{{ .Values.processor.image.repository }}:{{ .Values.processor.image.tag }}"
          imagePullPolicy: {{ .Values.processor.image.pullPolicy | default "IfNotPresent" }}
          ports:
            - containerPort: {{ .Values.processor.port }}

          {{- $procEnvFrom := include "app.componentEnvFrom" .Values.processor }}
          {{- if $procEnvFrom }}
          envFrom:
{{ $procEnvFrom | nindent 12 }}
          {{- end }}

          env:
            {{- include "app.extraEnvironmentVars" .Values.processor | nindent 12 }}

          {{- $procMounts := include "app.componentVolumeMounts" .Values.processor -}}
          {{- $procData  := include "app.dataStorage.processorVolumeMount" . -}}
          {{- if or $procMounts $procData }}
          volumeMounts:
            {{- if $procMounts }}
{{ $procMounts | nindent 12 }}
            {{- end }}
            {{- if $procData }}
{{ $procData | nindent 12 }}
            {{- end }}
          {{- end }}

        - name: {{ default "frontend" .Values.frontend.name }}
          image: "{{ .Values.frontend.image }}"
          imagePullPolicy: {{ .Values.frontend.pullPolicy | default "IfNotPresent" }}
          ports:
            - containerPort: {{ .Values.frontend.port }}

          {{- $feEnvFrom := include "app.componentEnvFrom" .Values.frontend }}
          {{- if $feEnvFrom }}
          envFrom:
{{ $feEnvFrom | nindent 12 }}
          {{- end }}

          env:
            {{- include "app.extraEnvironmentVars" .Values.frontend | nindent 12 }}

          {{ include "frontend.securityContext.container" . | nindent 10 }}
          {{ include "frontend.resources" . | nindent 10 }}

          {{- $feMounts := include "app.componentVolumeMounts" .Values.frontend -}}
          {{- $feData   := include "app.dataStorage.frontendVolumeMount" . -}}
          {{- if or $feMounts $feData }}
          volumeMounts:
            {{- if $feMounts }}
{{ $feMounts | nindent 12 }}
            {{- end }}
            {{- if $feData }}
{{ $feData | nindent 12 }}
            {{- end }}
          {{- end }}

        - name: {{ default "backend" .Values.backend.name }}
          image: "{{ .Values.backend.image }}"
          ports:
            - containerPort: {{ .Values.backend.port }}

          {{- $beEnvFrom := include "app.componentEnvFrom" .Values.backend }}
          {{- if $beEnvFrom }}
          envFrom:
{{ $beEnvFrom | nindent 12 }}
          {{- end }}

          env:
            {{- include "app.extraEnvironmentVars" .Values.backend | nindent 12 }}

          {{- $beMounts := include "app.componentVolumeMounts" .Values.backend -}}
          {{- $beData   := include "app.dataStorage.backendVolumeMount" . -}}
          {{- if or $beMounts $beData }}
          volumeMounts:
            {{- if $beMounts }}
{{ $beMounts | nindent 12 }}
            {{- end }}
            {{- if $beData }}
{{ $beData | nindent 12 }}
            {{- end }}
          {{- end }}

      volumes:
{{ include "app.podVolumes" . | nindent 8 }}
{{ include "app.dataStorage.podVolume" . | nindent 8 }}

      {{- include "imagePullSecrets" . | nindent 6 }}
