apiVersion: v2
appVersion: 1.1.7-rc.a2c0fac.20251014215313
description: Information about the architecture and makeup of the LTC's server infrastructure.
home: https://infrastructure-documentation.ltc.bcit.ca
icon: https://course-production.ltc.bcit.ca/favicon.ico
maintainers:
  - email: ltc_techops@bcit.ca
    name: BCIT LTC
    url: https://www.bcit.ca/learning-teaching-centre/
name: infrastructure-documentation
sources:
  - https://github.com/bcit-ltc/
  - https://github.com/bcit-ltc/infrastructure-documentation
version: 1.1.7-rc.a2c0fac.20251014215313
dependencies:
  - name: apps-common
    version: 0.1.0
    repository: https://bcit-ltc.github.io/helm-charts
