{{- define "nginx-unprivileged.configmap.tpl" -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    pid /tmp/nginx.pid; # Changed from /var/run/nginx.pid
    http {
      server {
          listen       8080; # Changed from default 80 port
          server_name  _;
          location / {
              root   /usr/share/nginx/html;
              index  index.html index.htm;
          }
      }
    }
{{- end -}}
{{- define "nginx-unprivileged.configmap" -}}
{{- include "nginx-unprivileged.util.merge" (append . "nginx-unprivileged.configmap.tpl") -}}
{{- end -}}
