apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "app.selectorLabels" . | nindent 8 }}
      {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: nginx
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          {{- with .Values.probes.readiness }}
          {{- if .enabled }}
          readinessProbe:
            httpGet:
              path: {{ .path | default "/" | quote }}
              port: http
            initialDelaySeconds: {{ .initialDelaySeconds | default 2 }}
            periodSeconds: {{ .periodSeconds | default 5 }}
          {{- end }}
          {{- end }}
          {{- with .Values.probes.liveness }}
          {{- if .enabled }}
          livenessProbe:
            httpGet:
              path: {{ .path | default "/" | quote }}
              port: http
            initialDelaySeconds: {{ .initialDelaySeconds | default 10 }}
            periodSeconds: {{ .periodSeconds | default 10 }}
          {{- end }}
          {{- end }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if .Values.volumes.tmp.enabled }}
          volumeMounts:
            - name: tmp
              mountPath: {{ .Values.volumes.tmp.mountPath | default "/tmp" | quote }}
          {{- end }}
      {{- if .Values.volumes.tmp.enabled }}
      volumes:
        - name: tmp
          emptyDir: {}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
