{{/*
SPDX-License-Identifier: MPL-2.0
*/}}

{{- template "app.serviceEnabled" . -}}
{{- if .serviceEnabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "app.name" . }}
  labels:
    helm.sh/chart: {{ include "app.chart" . }}
    app.kubernetes.io/name: {{ include "app.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
  annotations:
{{ template "app.service.annotations" .}}
spec:
  {{- if .Values.service.type}}
  type: {{ .Values.service.type }}
  {{- end}}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      {{- if and (.Values.service.nodePort) (eq (.Values.service.type | toString) "NodePort") }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "app.name" . }}

{{- end }}
