apiVersion: v2
name: course-workload-estimator
description: A time calculator to estimate the number of hours of work students might be expected to spend completing coursework.
version: 1.0.2
appVersion: "1.0.2"
home: https://course-workload-estimator.ltc.bcit.ca
maintainers:
  - name: BCIT LTC
    email: ltc_techops@bcit.ca
    url: https://www.bcit.ca/learning-teaching-centre/
sources:
  - https://github.com/bcit-ltc/
icon: https://course-production.ltc.bcit.ca/favicon.ico
