{{- if (default true .Values.service.enabled) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.name" . }}
  labels:
{{ include "app.labels" . | nindent 4 }}
  {{ include "app.service.annotations" . | nindent 2 }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.service.port | default 8080 }}
      targetPort: {{ .Values.service.targetPort | default .Values.service.port }}
      protocol: TCP
      name: http
  selector:
{{ include "app.selectorLabels" . | nindent 4 }}
{{- end }}
