{{- /*
Renders a ConfigMap for each item in:
  - .Values.frontend.configMounts
  - .Values.processor.configMounts

Each item should look like:
  - name: <configmap-name>
    mountPath: <ignored here>
    data:
      <key>: <value or |- block>

If no configMounts exist, this file renders nothing.
*/ -}}

{{- $root := . -}}
{{- $components := list .Values.frontend .Values.processor -}}

{{- range $c := $components }}
  {{- range $m := ($c.configMounts | default list) }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $m.name | quote }}
  labels:
{{ include "app.labels" $root | nindent 4 }}
data:
{{- if $m.data }}
{{ toYaml $m.data | nindent 2 }}
{{- end }}
  {{- end }}
{{- end }}
