replicaCount: 1

nameOverride: ""
fullnameOverride: ""

image:
  repository: nginxinc/nginx-unprivileged
  tag: "alpine3.22"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080      # container listens on 8080
  annotations: {}

podAnnotations: {}
podLabels: {}

# Probes (container listens on service.targetPort by default)
probes:
  readiness:
    enabled: true
    path: /
    initialDelaySeconds: 2
    periodSeconds: 5
  liveness:
    enabled: true
    path: /
    initialDelaySeconds: 10
    periodSeconds: 10

# Container-level security context
securityContext:
  runAsUser: 101
  runAsGroup: 101
  runAsNonRoot: true
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true

# Pod-level security context
podSecurityContext:
  runAsNonRoot: true

# Volumes
volumes:
  tmp:
    enabled: true
    mountPath: /tmp

resources: {}

# Scheduling
nodeSelector: {}
tolerations: []
affinity: {}
