name: Update chart index and publish OCI Helm charts

on:
  push:
    branches: [ main ]
  workflow_run:
    workflows: [ "Remotely-triggered chart bump & commit" ]  # fires when remote-bump finishes
    branches:   [ main ]
    types: [ completed ]

# Prevent runs from colliding across pushes to main
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  packages: write
  id-token: write

jobs:
  # Package changed charts and create GitHub Releases with .tgz assets
  chart-index-updater:
    name: Chart index updater
    runs-on: ubuntu-latest
    outputs:
      tags_json: ${{ steps.tags.outputs.list }}   # e.g., ["app-0.2.0","nginx-unprivileged-1.3.4"]
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Configure Git
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - uses: helm/chart-releaser-action@v1.6.0
        env:
          CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CR_SKIP_EXISTING: true

      # Collect ALL packaged tags from .cr-release-packages/*.tgz
      - name: Detect packaged chart tags
        id: tags
        run: |
          shopt -s nullglob
          files=(.cr-release-packages/*.tgz)
          if (( ${#files[@]} )); then
            tags=$(printf '%s\n' "${files[@]}" | sed -E 's,.*/(.*)\.tgz$,\1,' | jq -R . | jq -sc .)
          else
            tags="[]"
          fi
          echo "list=$tags" >> "$GITHUB_OUTPUT"
          echo "Packaged tags: $tags"

  # Publish all packaged charts from this run (matrix over tags)
  publish-charts:
    name: Publish OCI charts to GHCR
    needs: chart-index-updater
    if: ${{ needs.chart-index-updater.outputs.tags_json != '' && needs.chart-index-updater.outputs.tags_json != '[]' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tag: ${{ fromJson(needs.chart-index-updater.outputs.tags_json) }}
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - uses: azure/setup-helm@v4
        with: { version: v3.14.4 }

      # Single login that both Helm and Cosign can use (writes to ~/.docker/config.json)
      - name: Login to GHCR (helm)
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | helm registry login ghcr.io \
            -u "${{ github.actor }}" --password-stdin

      - name: Download chart assets for tag
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir -p dist
          gh release download "${{ matrix.tag }}" \
            --repo "${{ github.repository }}" \
            --pattern '*.tgz' \
            --dir dist

      - uses: sigstore/cosign-installer@v3

      - name: Push & sign chart(s) by digest (fail if exists)
        env:
          OWNER: ${{ github.repository_owner }}
        run: |
          set -euo pipefail
          shopt -s nullglob
          for pkg in dist/*.tgz; do
            name="$(helm show chart "$pkg" | awk -F': ' '/^name:/{print $2; exit}')"
            version="$(helm show chart "$pkg" | awk -F': ' '/^version:/{print $2; exit}')"
            repo="oci://ghcr.io/${OWNER}/oci"

            # Push will exit non-zero if the chart:version already exists -> job fails (as requested)
            PUSH_OUT="$(helm push "$pkg" "${repo}" | tee /dev/stderr)"

            # Extract the sha256 digest that Helm prints after a successful push
            DGST="$(printf '%s\n' "$PUSH_OUT" | sed -n -E 's/^[Dd]igest:[[:space:]]*(sha256:[0-9a-f]{64}).*$/\1/p')"
            if [[ -z "${DGST}" ]]; then
              echo "Failed to parse digest from helm push output"; exit 1
            fi

            REF="ghcr.io/${OWNER}/oci/${name}"
            echo "Signing ${REF}@${DGST} with Cosign (keyless)…"
            cosign sign --yes \
              -a "chart.name=${name}" \
              -a "chart.version=${version}" \
              -a "repo=${GITHUB_REPOSITORY}" \
              -a "workflow=${GITHUB_WORKFLOW}" \
              -a "sha=${GITHUB_SHA}" \
              "${REF}@${DGST}"
          done
