name: Update, release, and publish Helm charts

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      tag:
        description: 'Optional: release tag to publish (skip detection)'
        required: false

permissions:
  contents: write
  packages: write

jobs:
  release:
    name: Run chart-releaser
    runs-on: ubuntu-latest
    outputs:
      new_tag: ${{ steps.release_tag.outputs.tag }}   # ← publish will read this
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      # Mark the time right before chart-releaser runs
      - name: Mark start time
        id: t0
        run: echo "ts=$(date -u +%FT%TZ)" >> "$GITHUB_OUTPUT"

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      # Detect a release created during THIS run (createdAt >= t0)
      - name: Detect newly created release tag
        id: release_tag
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TS='${{ steps.t0.outputs.ts }}'
          TAG=$(gh release list --limit 50 --repo "${{ github.repository }}" \
            --json tagName,createdAt \
            --jq "[.[] | select(.createdAt >= \"${TS}\")][0].tagName" || true)
          echo "tag=${TAG}" >> "$GITHUB_OUTPUT"
          if [[ -z "$TAG" ]]; then
            echo "No new release created in this run."
          else
            echo "New release tag detected: $TAG"
          fi

  publish:
    name: Publish OCI charts to GHCR (if a new release exists)
    needs: release
    # Skip the entire job unless a tag is provided manually OR a new one was created
    if: ${{ (github.event_name == 'workflow_dispatch' && inputs.tag != '') || needs.release.outputs.new_tag != '' }}
    runs-on: ubuntu-latest
    steps:
      - name: Resolve tag (manual input or detected new tag)
        id: tag
        run: |
          if [[ -n "${{ github.event_name == 'workflow_dispatch' && inputs.tag || '' }}" ]]; then
            TAG="${{ inputs.tag }}"
          else
            TAG="${{ needs.release.outputs.new_tag }}"
          fi
          echo "tag=$TAG" >> "$GITHUB_OUTPUT"
          echo "Publishing tag: ${TAG}"

      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.4

      - name: Login to GHCR (password-stdin)
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "${GH_TOKEN}" | helm registry login ghcr.io \
            -u "${{ github.actor }}" \
            --password-stdin

      - name: Check release has *.tgz assets
        id: have_assets
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail
          COUNT=$(gh release view "${{ steps.tag.outputs.tag }}" --repo "${{ github.repository }}" \
            --json assets --jq '.assets | map(select(.name | test("\\.tgz$"))) | length' || echo 0)
          echo "count=$COUNT" >> "$GITHUB_OUTPUT"
          if [[ "$COUNT" -eq 0 ]]; then
            echo "Release has no .tgz assets; skipping."
          fi

      - name: Download chart assets for the tag
        if: ${{ steps.have_assets.outputs.count != '0' }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir -p dist
          gh release download "${{ steps.tag.outputs.tag }}" \
            --repo "${{ github.repository }}" \
            --pattern '*.tgz' \
            --dir dist

      - name: Push chart oci package(s) to GHCR
        if: ${{ steps.have_assets.outputs.count != '0' }}
        run: |
          shopt -s nullglob
          for pkg in dist/*.tgz; do
            echo "Pushing $pkg to GHCR…"
            helm push "$pkg" oci://ghcr.io/${{ github.repository_owner }}/oci
          done

      - name: Show pushed package name(s)
        if: ${{ steps.have_assets.outputs.count != '0' }}
        run: |
          for pkg in dist/*.tgz; do
            echo "Published: $pkg → ghcr.io/${{ github.repository_owner }}/oci"
          done
