{{- /*
Renders PVCs for:
  - .Values.frontend.storageMounts
  - .Values.processor.storageMounts

Each item:
  - name: <pvc-name> (required)
  - size: <e.g., 10Gi> (required)
  - accessMode: <ReadWriteOnce|ReadOnlyMany|ReadWriteMany> (default: ReadWriteOnce)
  - storageClass: <string|null> (optional, omitted if null/empty)
  - mountPath: <string> (ignored here; used by deployment mounts)
*/ -}}

{{- $root := . -}}
{{- $components := list .Values.frontend .Values.processor -}}

{{- range $c := $components }}
  {{- range $m := ($c.storageMounts | default list) }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $m.name | quote }}
  labels:
{{ include "app.labels" $root | nindent 4 }}
spec:
  accessModes:
    - {{ ($m.accessMode | default "ReadWriteOnce") | quote }}
  resources:
    requests:
      storage: {{ $m.size | quote }}
  {{- with $m.storageClass }}
  storageClassName: {{ . | quote }}
  {{- end }}
  {{- end }}
{{- end }}
